from permutation import Permutation


class PermutationGroup:
    """
    Permutation group generated by a given set of generators.
    You can check if the groups been generated, if it's abelian, and reference elements explicitly.
    """

    def __init__(self, generators, domain):
        self.domain = tuple(sorted(domain))
        self.identity = Permutation(lambda x: x, self.domain)
        self.elements = set(generators)
        self.elements.add(self.identity)

        self.generated = False
        self.abelian = None
        self._checked_pairs = set()
        self._refresh_index()

    def _refresh_index(self):
        """
        Maintain lookup from tuple representation to group element.
        """
        self.element_index = {g.image_tuple: g for g in self.elements}

    def get_element(self, image_tuple):
        """
        Return the group element with the given tuple representation.
        Example: get_element((0, 2, 1))
        """
        key = tuple(image_tuple)
        if key not in self.element_index:
            raise KeyError(f"No element found with image tuple {image_tuple}")
        return self.element_index[key]

    def _expand_from_pair(self, a, b):
        """
        Generate related pairs of elements:
        ab, ba, (ab)^-1, (ba)^-1

        Returns:
            new_elements (set): derived elements
            commute (bool): whether a and b commute
        """
        ab = a * b
        ba = b * a
        inv_ab = ab.inverse()
        inv_ba = ba.inverse()

        new_elements = {ab, ba, inv_ab, inv_ba}
        commute = (ab == ba)
        return new_elements, commute

    def partial_generate(self):
        """
        Perform one generation pass over unchecked pairs.
        Returns True if new elements were added, otherwise False.
        """
        current_elements = list(self.elements)
        new_elements = set()
        all_commute = True

        for a in current_elements:
            for b in current_elements:
                pair_key = (a.image_tuple, b.image_tuple)
                reverse_key = (b.image_tuple, a.image_tuple)

                if pair_key in self._checked_pairs or reverse_key in self._checked_pairs:
                    continue

                self._checked_pairs.add(pair_key)
                self._checked_pairs.add(reverse_key)

                derived_elements, commute = self._expand_from_pair(a, b)
                all_commute = all_commute and commute

                for g in derived_elements:
                    if g not in self.elements:
                        new_elements.add(g)

        if new_elements:
            self.elements.update(new_elements)
            self._refresh_index()
            self.generated = False
            self.abelian = None
            return True

        self.generated = True
        if self.abelian is None:
            self.abelian = all_commute
        return False

    def generate(self):
        """
        Fully generate the group by repeating passes until no new
        elements are found.
        """
        while self.partial_generate():
            pass

        if self.abelian is None:
            self.abelian = self.is_abelian()

    def is_generated(self):
        return self.generated

    def is_abelian(self):
        if self.abelian is not None and self.generated:
            return self.abelian

        elements = list(self.elements)
        for a in elements:
            for b in elements:
                if a * b != b * a:
                    self.abelian = False
                    return False

        self.abelian = True
        return True

    def conjugate_by(self, perm):
        """
        Return the conjugate of this group by a permutation:
        G^perm = { perm^{-1} g perm | g in G }
        """
        if perm.domain != self.domain:
            raise ValueError("Permutation must have same domain as group.")

        new_elements = {
            g.conjugate_by(perm) for g in self.elements
        }

        new_group = PermutationGroup(new_elements, self.domain)
        new_group.generate()
        return new_group

    def __len__(self):
        return len(self.elements)